# Generated by Django 5.1.7 on 2025-04-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('room_service', 'Room Service')], help_text='Staff role to which this rate applies.', max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Salary per completed task for this role.', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('room_service', 'Room Service')], help_text='The staff role that completed the task.', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The payment amount for the completed task.', max_digits=8)),
                ('completed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of task completion.')),
                ('description', models.TextField(blank=True, help_text='Optional description of the completed task.')),
            ],
        ),
    ]
