# Generated by Django 5.1.7 on 2025-03-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('manager', 'Manager'), ('room_service', 'Room Service')], max_length=20),
        ),
    ]
