# Generated by Django 5.1.7 on 2025-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role_taskpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('manager', 'Manager'), ('room_service', 'Room Service')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TaskPayment',
        ),
    ]
