# Generated by Django 5.1.7 on 2025-04-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='dirty_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
